# Generated by Django 5.2.14 on 2026-05-24 15:17
""" Migrations for the contacts app. """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_case_insensitive_group_tag_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_scalar_sync",
            field=models.BooleanField(
                default=False,
                help_text="Managed by Contact.email via sync_primary_records().",
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="is_scalar_sync",
            field=models.BooleanField(
                default=False,
                help_text="Managed by Contact.phone via sync_primary_records().",
            ),
        ),
    ]
